export const theme = {
  colors: {
    background: '#f8fbff',
    primary: '#000000',
    onPrimary: '#ffffff',
    secondary: '#006a61', // Community Teal
    onSecondary: '#ffffff',
    secondaryContainer: '#86f2e4',
    onSecondaryContainer: '#006f66',
    surface: '#f7f9fb',
    surfaceDim: '#d8dadc',
    surfaceBright: '#f7f9fb',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f4f6',
    surfaceContainer: '#eceef0',
    surfaceContainerHigh: '#e6e8ea',
    surfaceContainerHighest: '#e0e3e5',
    onSurface: '#191c1e',
    onSurfaceVariant: '#45464d',
    inverseSurface: '#2d3133',
    inverseOnSurface: '#eff1f3',
    outline: '#76777d',
    outlineVariant: '#c6c6cd',
    primaryFixed: '#dae2fd',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    base: 4,
    containerMarginMobile: 16,
    containerMarginDesktop: 48,
    gutter: 16,
  },
  rounded: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    headlineXl: {
      fontSize: 32,
      fontWeight: '700' as const,
      lineHeight: 40,
      letterSpacing: -0.64,
    },
    headlineLg: {
      fontSize: 24,
      fontWeight: '700' as const,
      lineHeight: 32,
      letterSpacing: -0.24,
    },
    headlineLgMobile: {
      fontSize: 20,
      fontWeight: '700' as const,
      lineHeight: 28,
    },
    headlineMd: {
      fontSize: 18,
      fontWeight: '600' as const,
      lineHeight: 24,
    },
    bodyLg: {
      fontSize: 16,
      fontWeight: '400' as const,
      lineHeight: 24,
    },
    bodyMd: {
      fontSize: 14,
      fontWeight: '400' as const,
      lineHeight: 20,
    },
    labelMd: {
      fontSize: 12,
      fontWeight: '600' as const,
      lineHeight: 16,
      letterSpacing: 0.6,
    },
    button: {
      fontSize: 14,
      fontWeight: '600' as const,
      lineHeight: 20,
    },
  },
};
